import { BaseSeeder } from '@adonisjs/lucid/seeders'
import CombatSkill from '#models/combat_skill'

export default class extends BaseSeeder {
  async run() {
    const skills = [
      // ═══════════════════════════════════════════
      // HACKER — Offensive hacking programs
      // ═══════════════════════════════════════════
      {
        name: 'Breach Protocol',
        nameEn: 'Breach Protocol',
        description: 'Hack les defenses de l\'ennemi. Reduit sa DEF de 50% pendant 2 tours.',
        descriptionEn: 'Hacks the enemy\'s defenses. Reduces their DEF by 50% for 2 turns.',
        spec: 'hacker',
        tierRequired: 3,
        effectType: 'debuff_def',
        effectValue: 50,
        duration: 2,
        cooldown: 4,
        icon: 'breach',
      },
      {
        name: 'Short Circuit',
        nameEn: 'Short Circuit',
        description: 'Decharge electrique directe. Inflige des degats purs qui ignorent la DEF.',
        descriptionEn: 'Direct electrical discharge. Deals pure damage that ignores DEF.',
        spec: 'hacker',
        tierRequired: 7,
        effectType: 'pure_damage',
        effectValue: 150,
        duration: 0,
        cooldown: 3,
        icon: 'circuit',
      },
      {
        name: 'Backdoor',
        nameEn: 'Backdoor',
        description: 'Infiltre le systeme ennemi. Vole des credits et inflige des degats.',
        descriptionEn: 'Infiltrates the enemy system. Steals credits and deals damage.',
        spec: 'hacker',
        tierRequired: 12,
        effectType: 'steal_damage',
        effectValue: 120,
        duration: 0,
        cooldown: 4,
        icon: 'backdoor',
      },
      {
        name: 'Kernel Panic',
        nameEn: 'Kernel Panic',
        description: 'Crash total du systeme. Degats massifs + stun 1 tour.',
        descriptionEn: 'Total system crash. Massive damage + stun for 1 turn.',
        spec: 'hacker',
        tierRequired: 18,
        effectType: 'damage_stun',
        effectValue: 200,
        duration: 1,
        cooldown: 5,
        icon: 'kernel',
      },

      // ═══════════════════════════════════════════
      // NETRUNNER — Control & support programs
      // ═══════════════════════════════════════════
      {
        name: 'Ping Scan',
        nameEn: 'Ping Scan',
        description: 'Analyse la cible. Ta prochaine attaque sera un coup critique garanti.',
        descriptionEn: 'Scans the target. Your next attack is a guaranteed critical hit.',
        spec: 'netrunner',
        tierRequired: 3,
        effectType: 'guaranteed_crit',
        effectValue: 0,
        duration: 1,
        cooldown: 3,
        icon: 'ping',
      },
      {
        name: 'ICE Breaker',
        nameEn: 'ICE Breaker',
        description: 'Brise les protections. Retire tous les buffs ennemis + degats moderes.',
        descriptionEn: 'Breaks defenses. Removes all enemy buffs + moderate damage.',
        spec: 'netrunner',
        tierRequired: 7,
        effectType: 'purge_damage',
        effectValue: 80,
        duration: 0,
        cooldown: 3,
        icon: 'ice',
      },
      {
        name: 'Neural Overload',
        nameEn: 'Neural Overload',
        description: 'Surcharge le cortex de l\'ennemi. Stun 1 tour + degats.',
        descriptionEn: 'Overloads the enemy\'s cortex. Stun for 1 turn + damage.',
        spec: 'netrunner',
        tierRequired: 12,
        effectType: 'damage_stun',
        effectValue: 100,
        duration: 1,
        cooldown: 4,
        icon: 'overload',
      },
      {
        name: 'System Restore',
        nameEn: 'System Restore',
        description: 'Programme de soin avance. Restaure 40% des HP max.',
        descriptionEn: 'Advanced healing program. Restores 40% of max HP.',
        spec: 'netrunner',
        tierRequired: 18,
        effectType: 'heal_percent',
        effectValue: 40,
        duration: 0,
        cooldown: 5,
        icon: 'restore',
      },

      // ═══════════════════════════════════════════
      // STREET SAMURAI — Physical combat techniques
      // ═══════════════════════════════════════════
      {
        name: 'Wired Reflexes',
        nameEn: 'Wired Reflexes',
        description: 'Implants de reflexes actives. Frappe deux fois d\'affilee.',
        descriptionEn: 'Activated reflex implants. Strike twice in a row.',
        spec: 'samurai',
        tierRequired: 3,
        effectType: 'double_hit',
        effectValue: 0,
        duration: 0,
        cooldown: 3,
        icon: 'reflex',
      },
      {
        name: 'Mono-Edge Slash',
        nameEn: 'Mono-Edge Slash',
        description: 'Lame monomoleculaire. Degats lourds + saignement pendant 3 tours.',
        descriptionEn: 'Monomolecular blade. Heavy damage + bleed for 3 turns.',
        spec: 'samurai',
        tierRequired: 7,
        effectType: 'damage_dot',
        effectValue: 130,
        duration: 3,
        cooldown: 4,
        icon: 'mono',
      },
      {
        name: 'Subdermal Shield',
        nameEn: 'Subdermal Shield',
        description: 'Active le blindage sous-cutane. Absorbe le prochain coup completement.',
        descriptionEn: 'Activates subdermal plating. Fully absorbs the next hit.',
        spec: 'samurai',
        tierRequired: 12,
        effectType: 'shield',
        effectValue: 0,
        duration: 1,
        cooldown: 5,
        icon: 'shield',
      },
      {
        name: 'Adrenaline Surge',
        nameEn: 'Adrenaline Surge',
        description: 'Injection d\'adrenaline. Critique garanti + triple degats.',
        descriptionEn: 'Adrenaline injection. Guaranteed crit + triple damage.',
        spec: 'samurai',
        tierRequired: 18,
        effectType: 'mega_strike',
        effectValue: 300,
        duration: 0,
        cooldown: 6,
        icon: 'adrenaline',
      },

      // ═══════════════════════════════════════════
      // CHROME DEALER — Tech utility programs
      // ═══════════════════════════════════════════
      {
        name: 'Deploy Turret',
        nameEn: 'Deploy Turret',
        description: 'Deploie une tourelle automatique. Inflige des degats bonus pendant 3 tours.',
        descriptionEn: 'Deploys an automatic turret. Deals bonus damage for 3 turns.',
        spec: 'chrome_dealer',
        tierRequired: 3,
        effectType: 'turret',
        effectValue: 40,
        duration: 3,
        cooldown: 4,
        icon: 'turret',
      },
      {
        name: 'Repair Nanobots',
        nameEn: 'Repair Nanobots',
        description: 'Active les nanobots de reparation. Restaure 30% des HP max.',
        descriptionEn: 'Activates repair nanobots. Restores 30% of max HP.',
        spec: 'chrome_dealer',
        tierRequired: 7,
        effectType: 'heal_percent',
        effectValue: 30,
        duration: 0,
        cooldown: 4,
        icon: 'nanobots',
      },
      {
        name: 'EMP Blast',
        nameEn: 'EMP Blast',
        description: 'Impulsion electromagnetique. Reduit l\'ATK de l\'ennemi de 50% pendant 2 tours.',
        descriptionEn: 'Electromagnetic pulse. Reduces enemy ATK by 50% for 2 turns.',
        spec: 'chrome_dealer',
        tierRequired: 12,
        effectType: 'debuff_atk',
        effectValue: 50,
        duration: 2,
        cooldown: 4,
        icon: 'emp',
      },
      {
        name: 'Chrome Overcharge',
        nameEn: 'Chrome Overcharge',
        description: 'Suralimente tous tes implants. ATK et DEF +50% pendant 3 tours.',
        descriptionEn: 'Supercharges all your implants. ATK and DEF +50% for 3 turns.',
        spec: 'chrome_dealer',
        tierRequired: 18,
        effectType: 'buff_all',
        effectValue: 50,
        duration: 3,
        cooldown: 6,
        icon: 'overcharge',
      },
    ] as const

    for (const skill of skills) {
      await CombatSkill.updateOrCreate({ name: skill.name, spec: skill.spec }, skill as any)
    }
  }
}
